import React from 'react';
import './ReportTemplate.css';

const ReportTemplate = ({ research, businesses, user, analytics }) => {
  const formatDate = (date) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return (
    <div className="report-container">
      {/* COVER PAGE */}
      <div className="report-page cover-page">
        <div className="cover-content">
          <div className="logo-large">SCRUTINA</div>
          <div className="cover-subtitle">AI-Powered Business Intelligence Report</div>
          
          <div className="query-box">
            <div className="query-text">{research.query}</div>
          </div>
          
          <div className="cover-meta">
            <div className="meta-row">
              <span className="meta-label">Generated Date:</span>
              <span className="meta-value">{formatDate(new Date())}</span>
            </div>
            <div className="meta-row">
              <span className="meta-label">Generated By:</span>
              <span className="meta-value">{user.fullName || user.email}</span>
            </div>
            <div className="meta-row">
              <span className="meta-label">Research ID:</span>
              <span className="meta-value">{research._id}</span>
            </div>
          </div>
          
          <div className="cover-footer">
            Powered by Advanced AI & Multi-Source Intelligence
          </div>
        </div>
      </div>

      {/* EXECUTIVE DASHBOARD */}
      <div className="report-page">
        <div className="page-header">
          <h2>Executive Dashboard</h2>
        </div>
        
        <div className="stats-grid">
          <div className="stat-card blue">
            <div className="stat-icon">🏢</div>
            <div className="stat-value">{analytics.totalBusinesses}</div>
            <div className="stat-label">Businesses Found</div>
            <div className="stat-desc">Across all research sessions</div>
          </div>
          
          <div className="stat-card green">
            <div className="stat-icon">✓</div>
            <div className="stat-value">{analytics.verifiedBusinesses}</div>
            <div className="stat-label">Verified Businesses</div>
            <div className="stat-desc">High quality data</div>
          </div>
          
          <div className="stat-card yellow">
            <div className="stat-icon">⭐</div>
            <div className="stat-value">{analytics.avgTrustScore}%</div>
            <div className="stat-label">Average Trust Score</div>
            <div className="stat-desc">Data reliability index</div>
          </div>
          
          <div className="stat-card red">
            <div className="stat-icon">🛡</div>
            <div className="stat-value">{analytics.avgSecurityScore}%</div>
            <div className="stat-label">Average Security Score</div>
            <div className="stat-desc">Security posture</div>
          </div>
        </div>
        
        <div className="summary-section">
          <h3>Research Summary</h3>
          <div className="summary-grid">
            <div className="summary-item">
              <span className="summary-label">Query:</span>
              <span className="summary-value">{research.query}</span>
            </div>
            <div className="summary-item">
              <span className="summary-label">Status:</span>
              <span className="summary-value">{research.status.toUpperCase()}</span>
            </div>
            <div className="summary-item">
              <span className="summary-label">Duration:</span>
              <span className="summary-value">
                {research.summary?.durationSeconds ? research.summary.durationSeconds.toFixed(2) + 's' : 'N/A'}
              </span>
            </div>
            <div className="summary-item">
              <span className="summary-label">Sources:</span>
              <span className="summary-value">Multi-Source Intelligence</span>
            </div>
          </div>
        </div>
        
        <div className="page-footer">
          <span>SCRUTINA - AI-Powered Business Intelligence Platform</span>
          <span>Confidential Report</span>
        </div>
      </div>

      {/* AI EXECUTIVE SUMMARY */}
      <div className="report-page">
        <div className="page-header">
          <h2>AI Executive Summary</h2>
        </div>
        
        <div className="intel-card">
          <div className="intel-header">
            <span className="intel-icon">🤖</span>
            <h3>AI-Generated Insights</h3>
          </div>
          <ul className="intel-list">
            <li>{analytics.totalBusinesses} businesses analyzed with {analytics.verifiedPercentage}% verification rate</li>
            <li>Average trust score of {analytics.avgTrustScore}% indicates {analytics.avgTrustScore >= 70 ? 'strong' : 'moderate'} data credibility</li>
            <li>Most common industry: {analytics.insights.mostCommonIndustry.industry} ({analytics.insights.mostCommonIndustry.count} businesses)</li>
            {analytics.insights.mostCommonService.service !== 'N/A' && (
              <li>Top service offered: {analytics.insights.mostCommonService.service}</li>
            )}
            <li>Highest security score: {analytics.insights.highestSecurity.securityScore || 0}% by {analytics.insights.highestSecurity.name || analytics.insights.highestSecurity.businessName}</li>
          </ul>
        </div>
        
        <div className="section">
          <h3>Business Strengths</h3>
          <p>
            Verified businesses demonstrate strong online presence with comprehensive contact information,
            professional certifications, and active social media profiles. Security implementation meets
            industry standards with HTTPS adoption and proper security headers.
          </p>
        </div>
        
        <div className="section">
          <h3>Business Risks</h3>
          <p>
            {analytics.avgSecurityScore < 70 ? 'Some businesses show security vulnerabilities requiring immediate attention. ' : ''}
            {analytics.verifiedPercentage < 70 ? 'Lower verification rates suggest incomplete business information. ' : ''}
            Continuous monitoring and verification recommended for maintaining data accuracy.
          </p>
        </div>
        
        <div className="section">
          <h3>Overall Assessment</h3>
          <p>
            {analytics.avgTrustScore >= 75 && analytics.avgSecurityScore >= 75
              ? `This research demonstrates exceptional business quality with ${analytics.verifiedPercentage}% verification rate and strong security implementation. The analyzed businesses show comprehensive data credibility and professional digital presence. Recommended for business engagement.`
              : analytics.avgTrustScore >= 60
              ? `The research reveals good business quality with moderate verification rates. Most businesses demonstrate acceptable credibility and security standards. Additional due diligence recommended for critical partnerships.`
              : `This analysis shows mixed business quality with verification improvements needed. Enhanced data validation and security assessments recommended before proceeding with business transactions.`}
          </p>
        </div>
        
        <div className="page-footer">
          <span>SCRUTINA - Confidential Report</span>
          <span>Page 3</span>
        </div>
      </div>

      {/* MARKET INSIGHTS */}
      <div className="report-page">
        <div className="page-header">
          <h2>Market Intelligence Dashboard</h2>
        </div>
        
        {analytics.industryDistribution.length > 0 && (
          <div className="chart-section">
            <h3>Industry Distribution</h3>
            <div className="bar-chart">
              {analytics.industryDistribution.map((item, idx) => (
                <div key={idx} className="bar-item">
                  <div className="bar-label">
                    <span>{item.industry}</span>
                    <span>{item.count} ({item.percentage}%)</span>
                  </div>
                  <div className="bar-track">
                    <div className="bar-fill" style={{ width: `${item.percentage}%` }}>
                      {item.percentage}%
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {analytics.trustScoreDistribution.length > 0 && (
          <div className="chart-section">
            <h3>Trust Score Distribution</h3>
            <div className="bar-chart">
              {analytics.trustScoreDistribution.map((item, idx) => (
                <div key={idx} className="bar-item">
                  <div className="bar-label">
                    <span>{item.range}</span>
                    <span>{item.count} businesses ({item.percentage}%)</span>
                  </div>
                  <div className="bar-track">
                    <div className={`bar-fill ${idx === 0 ? 'green' : idx === 1 ? 'blue' : idx === 2 ? 'yellow' : 'red'}`} style={{ width: `${item.percentage}%` }}>
                      {item.percentage}%
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        <div className="page-footer">
          <span>SCRUTINA - Confidential Report</span>
          <span>Page 4</span>
        </div>
      </div>

      {/* BUSINESS DIRECTORY */}
      {businesses.map((business, index) => {
        const isNewPage = index % 3 === 0;
        const isLastInPage = (index + 1) % 3 === 0 || index === businesses.length - 1;
        
        if (isNewPage) {
          return (
            <React.Fragment key={index}>
              <div className="report-page business-directory-page">
                <div className="page-header">
                  <h2>Business Directory</h2>
                </div>
                
                <div className="business-card-pdf">
                  <div className="business-header-pdf">
                    <div className="business-info-pdf">
                      <div className="business-name-pdf">{business.name || business.businessName}</div>
                      <div className="business-industry-pdf">{business.industry || 'N/A'}</div>
                    </div>
                    <div className="business-badges-pdf">
                      <div className="badge-pdf trust">⭐ {business.verificationScore || 0}%</div>
                      <div className="badge-pdf security">🛡 {business.securityScore || 0}%</div>
                      {business.verificationStatus === 'VERIFIED' && (
                        <div className="badge-pdf verified">✓</div>
                      )}
                    </div>
                  </div>
                  
                  <div className="business-contacts-pdf">
                    {business.phone && business.phone !== 'N/A' && (
                      <div className="contact-item-pdf">📞 {business.phone}</div>
                    )}
                    {business.email && business.email !== 'N/A' && (
                      <div className="contact-item-pdf">📧 {business.email}</div>
                    )}
                    {business.website && (
                      <div className="contact-item-pdf">🌐 {business.website}</div>
                    )}
                    {business.address && (
                      <div className="contact-item-pdf">📍 {business.address.substring(0, 80)}{business.address.length > 80 ? '...' : ''}</div>
                    )}
                  </div>
                  
                  {business.description && (
                    <div className="business-description-pdf">
                      {business.description.substring(0, 200)}{business.description.length > 200 ? '...' : ''}
                    </div>
                  )}
                  
                  {business.services && business.services.length > 0 && (
                    <div className="business-services-pdf">
                      {business.services.slice(0, 5).map((service, idx) => (
                        <span key={idx} className="service-badge-pdf">{service}</span>
                      ))}
                    </div>
                  )}
                </div>
                
                {isLastInPage && (
                  <div className="page-footer">
                    <span>SCRUTINA - Confidential Report</span>
                    <span>Page {5 + Math.floor(index / 3)}</span>
                  </div>
                )}
              </div>
            </React.Fragment>
          );
        } else {
          return (
            <React.Fragment key={index}>
              <div className="business-card-pdf">
                <div className="business-header-pdf">
                  <div className="business-info-pdf">
                    <div className="business-name-pdf">{business.name || business.businessName}</div>
                    <div className="business-industry-pdf">{business.industry || 'N/A'}</div>
                  </div>
                  <div className="business-badges-pdf">
                    <div className="badge-pdf trust">⭐ {business.verificationScore || 0}%</div>
                    <div className="badge-pdf security">🛡 {business.securityScore || 0}%</div>
                    {business.verificationStatus === 'VERIFIED' && (
                      <div className="badge-pdf verified">✓</div>
                    )}
                  </div>
                </div>
                
                <div className="business-contacts-pdf">
                  {business.phone && business.phone !== 'N/A' && (
                    <div className="contact-item-pdf">📞 {business.phone}</div>
                  )}
                  {business.email && business.email !== 'N/A' && (
                    <div className="contact-item-pdf">📧 {business.email}</div>
                  )}
                  {business.website && (
                    <div className="contact-item-pdf">🌐 {business.website}</div>
                  )}
                  {business.address && (
                    <div className="contact-item-pdf">📍 {business.address.substring(0, 80)}{business.address.length > 80 ? '...' : ''}</div>
                  )}
                </div>
                
                {business.description && (
                  <div className="business-description-pdf">
                    {business.description.substring(0, 200)}{business.description.length > 200 ? '...' : ''}
                  </div>
                )}
                
                {business.services && business.services.length > 0 && (
                  <div className="business-services-pdf">
                    {business.services.slice(0, 5).map((service, idx) => (
                      <span key={idx} className="service-badge-pdf">{service}</span>
                    ))}
                  </div>
                )}
              </div>
              
              {isLastInPage && (
                <div className="page-footer">
                  <span>SCRUTINA - Confidential Report</span>
                  <span>Page {5 + Math.floor(index / 3)}</span>
                </div>
              )}
            </React.Fragment>
          );
        }
      })}

      {/* FINAL PAGE - EXECUTIVE INSIGHTS */}
      <div className="report-page">
        <div className="page-header">
          <h2>Executive Insights</h2>
        </div>
        
        <div className="insights-grid">
          <div className="insight-card">
            <div className="insight-icon">🏆</div>
            <div className="insight-value">{analytics.insights.mostTrusted.verificationScore || 0}%</div>
            <div className="insight-label">Highest Trust Score</div>
            <div className="insight-business">{analytics.insights.mostTrusted.name || analytics.insights.mostTrusted.businessName}</div>
          </div>
          
          <div className="insight-card">
            <div className="insight-icon">🛡</div>
            <div className="insight-value">{analytics.insights.highestSecurity.securityScore || 0}%</div>
            <div className="insight-label">Highest Security Score</div>
            <div className="insight-business">{analytics.insights.highestSecurity.name || analytics.insights.highestSecurity.businessName}</div>
          </div>
          
          <div className="insight-card">
            <div className="insight-icon">📊</div>
            <div className="insight-value">{analytics.insights.mostCommonIndustry.industry}</div>
            <div className="insight-label">Most Common Industry</div>
            <div className="insight-business">{analytics.insights.mostCommonIndustry.count} businesses</div>
          </div>
          
          <div className="insight-card">
            <div className="insight-icon">⚙️</div>
            <div className="insight-value">{analytics.insights.mostCommonService.service}</div>
            <div className="insight-label">Top Service</div>
            <div className="insight-business">{analytics.insights.mostCommonService.count} providers</div>
          </div>
        </div>
        
        <div className="recommendations-card">
          <h3>📋 Overall Recommendations</h3>
          <ul>
            <li>{analytics.verifiedBusinesses} verified businesses suitable for immediate engagement</li>
            <li>Focus on businesses with trust scores above {analytics.avgTrustScore}% for optimal results</li>
            <li>{analytics.insights.mostCommonIndustry.industry} sector shows highest business concentration</li>
            <li>Continuous monitoring recommended for maintaining data accuracy</li>
            <li>Leverage multi-source intelligence for comprehensive due diligence</li>
          </ul>
        </div>
        
        <div className="disclaimer">
          <strong>Disclaimer:</strong> This report is generated by SCRUTINA AI-powered business intelligence platform.
          Data accuracy depends on publicly available information and multi-source verification.
          Users should conduct additional due diligence for critical business decisions.
        </div>
        
        <div className="page-footer">
          <span>SCRUTINA - Confidential Report - End of Document</span>
          <span>Final Page</span>
        </div>
      </div>
    </div>
  );
};

export default ReportTemplate;
